# Generated by Django 4.2.7 on 2025-11-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulseway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsewayaction',
            name='action_type',
            field=models.CharField(choices=[('script', 'Script Execution'), ('patch', 'Patch Installation'), ('reboot', 'Device Reboot'), ('site_create', 'Site Creation'), ('group_create', 'Group Creation'), ('automation_create', 'Automation Task Creation'), ('automation_run', 'Automation Task Execution')], max_length=20),
        ),
    ]
