# Generated by Django 4.2.7 on 2025-11-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulseway', '0002_alter_pulsewayaction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsewayaction',
            name='action_type',
            field=models.CharField(choices=[('script', 'Script Execution'), ('patch', 'Patch Installation'), ('reboot', 'Device Reboot'), ('site_create', 'Site Creation'), ('site_update', 'Site Update'), ('site_delete', 'Site Deletion'), ('group_create', 'Group Creation'), ('group_update', 'Group Update'), ('group_delete', 'Group Deletion'), ('automation_create', 'Automation Task Creation'), ('automation_run', 'Automation Task Execution')], max_length=20),
        ),
    ]
