# Generated by Django 4.2.7 on 2026-02-15 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_link_companies'),
        ('pulseway', '0003_alter_pulsewayaction_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulsewayDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulseway_devices', to='rbac.company')),
            ],
        ),
        migrations.CreateModel(
            name='PulsewayPatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('installed', 'Installed'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulseway_patches', to='rbac.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulseway.pulsewaydevice')),
            ],
        ),
    ]
