# Generated by Django 4.2.7 on 2026-03-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulseway', '0004_pulsewaydevice_pulsewaypatchreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulsewayOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('device_count', models.IntegerField(default=0)),
                ('online_devices', models.IntegerField(default=0)),
                ('offline_devices', models.IntegerField(default=0)),
                ('pending_patches', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PulsewayPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_id', models.CharField(max_length=100)),
                ('patch_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('install_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PulsewayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=100, unique=True)),
                ('report_name', models.CharField(max_length=200)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('report_type', models.CharField(max_length=100)),
                ('report_data', models.JSONField()),
                ('generated_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PulsewaySync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=50)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('records_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pulsewaydevice',
            name='company',
        ),
        migrations.AddField(
            model_name='pulsewaydevice',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pulsewaydevice',
            name='disk_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pulsewaydevice',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pulsewaydevice',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pulsewaydevice',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pulsewaydevice',
            name='memory_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pulsewaydevice',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pulsewaydevice',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pulsewaydevice',
            name='pending_patches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pulsewaydevice',
            name='site_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pulsewaydevice',
            name='uptime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pulsewaydevice',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pulsewaydevice',
            name='status',
            field=models.CharField(default='offline', max_length=20),
        ),
        migrations.DeleteModel(
            name='PulsewayPatchReport',
        ),
        migrations.AddField(
            model_name='pulsewaypatch',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='pulseway.pulsewaydevice'),
        ),
        migrations.AlterUniqueTogether(
            name='pulsewaypatch',
            unique_together={('device', 'patch_id')},
        ),
    ]
