# Generated by Django 4.2.7 on 2026-03-24 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0009_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('laptop', 'Laptop')], max_length=20)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('imei', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('managed', 'Managed'), ('staged', 'Staged'), ('enrollment_pending', 'Enrollment Pending'), ('retired', 'Retired'), ('active', 'Active'), ('inactive', 'Inactive')], default='managed', max_length=20)),
                ('enrollment_type', models.CharField(blank=True, max_length=100)),
                ('enrollment_time', models.DateTimeField(blank=True, null=True)),
                ('last_contact_time', models.DateTimeField(blank=True, null=True)),
                ('associated_groups', models.IntegerField(default=0)),
                ('profile_count', models.IntegerField(default=0)),
                ('apps_count', models.IntegerField(default=0)),
                ('is_supervised', models.BooleanField(default=False)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('storage_total', models.BigIntegerField(blank=True, null=True)),
                ('storage_used', models.BigIntegerField(blank=True, null=True)),
                ('free_space_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('location_updated', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MdmCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10, unique=True)),
                ('device_count', models.IntegerField(default=0)),
                ('no_of_devices', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mdm_customer', to='rbac.company')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('jailbreak', 'Jailbreak/Root Detected'), ('malware', 'Malware Detected'), ('policy_violation', 'Policy Violation'), ('unauthorized_app', 'Unauthorized App'), ('location_violation', 'Location Violation'), ('failed_login', 'Failed Login Attempt')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.device')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('profile_type', models.CharField(default='configuration', max_length=50)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mdm_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.mdmcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='MdmUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(default='user', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mdm_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.mdmcustomer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_personal_apps', models.BooleanField(default=True)),
                ('require_passcode', models.BooleanField(default=True)),
                ('auto_enrollment', models.BooleanField(default=False)),
                ('enrollment_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mdm_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mdm.mdmcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('devices', models.ManyToManyField(blank=True, to='mdm.device')),
                ('mdm_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.mdmcustomer')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='mdm_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.mdmcustomer'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.mdmuser'),
        ),
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('is_system_app', models.BooleanField(default=False)),
                ('is_managed', models.BooleanField(default=False)),
                ('install_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.device')),
            ],
            options={
                'unique_together': {('device', 'package_name')},
            },
        ),
        migrations.CreateModel(
            name='AppPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200)),
                ('policy_type', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block'), ('required', 'Required')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mdm_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.mdmcustomer')),
            ],
            options={
                'unique_together': {('mdm_customer', 'package_name')},
            },
        ),
    ]
