# Generated by Django 4.2.7 on 2026-04-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('office365', 'Office 365'), ('datto', 'Datto BCDR')], max_length=30)),
                ('company_key', models.CharField(blank=True, max_length=50)),
                ('data_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('source', 'company_key', 'data_type')},
            },
        ),
    ]
