# Generated by Django 4.2.7 on 2026-02-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_userprofile_address_userprofile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, unique=True)),
                ('total_licenses', models.IntegerField(default=0)),
                ('license_type', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('alert_sent_one_month', models.BooleanField(default=False)),
                ('alert_sent_one_week', models.BooleanField(default=False)),
            ],
        ),
    ]
