# Generated by Django 4.2.7 on 2026-03-26 01:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_licenses', models.IntegerField(default=0)),
                ('used_licenses', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('license_type', models.CharField(default='Standard', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='rbac.company')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.package')),
            ],
            options={
                'unique_together': {('company', 'package')},
            },
        ),
    ]
