# Generated by Django 4.2.29 on 2026-05-05 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0011_company_contact_email_licenserenewelnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianCompanyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_accesses', to='rbac.company')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_company_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technician Company Access',
                'verbose_name_plural': 'Technician Company Accesses',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
