# Generated by Django 4.2.7 on 2026-03-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync_time', models.DateTimeField()),
                ('total_tickets_synced', models.IntegerField(default=0)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sync_status',
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='manage_engine_id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('subject', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, max_length=100)),
                ('priority', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('requester_name', models.CharField(blank=True, max_length=200)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('technician_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket_cache',
                'indexes': [models.Index(fields=['created_at', 'status'], name='ticket_cach_created_6e47f9_idx'), models.Index(fields=['company_name', 'created_at'], name='ticket_cach_company_554a2e_idx'), models.Index(fields=['technician_name', 'created_at'], name='ticket_cach_technic_9f7ed7_idx')],
            },
        ),
    ]
