# Generated by Django 4.2.7 on 2026-03-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_syncstatus_remove_ticket_manage_engine_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcache',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
