# Generated by Django 4.2.29 on 2026-04-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticketcache_requester_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageEngineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('is_technician', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'me_user_cache',
                'indexes': [models.Index(fields=['is_technician'], name='me_user_cac_is_tech_793aa8_idx'), models.Index(fields=['company_name'], name='me_user_cac_company_3e5dd4_idx')],
            },
        ),
    ]
